package com.demo.artio.dictionary;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Writes a {@link FixDictionary} back out as the XML Artio's {@code DictionaryParser} reads.
 *
 * <p>The output is written by hand rather than through a {@code Transformer} so the element order
 * and indentation are fixed: two dictionaries that differ only in whitespace produce identical
 * bytes, which is what makes the idempotency check a byte comparison.</p>
 */
public final class ArtioDictionaryWriter {

    private static final String INDENT = "  ";

    public void write(final FixDictionary dictionary, final Path file) throws IOException {
        final Path parent = file.toAbsolutePath().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.writeString(file, toXml(dictionary), StandardCharsets.UTF_8);
    }

    public void write(final FixDictionary dictionary, final Writer out) throws IOException {
        out.write(toXml(dictionary));
    }

    public String toXml(final FixDictionary dictionary) {
        final StringBuilder xml = new StringBuilder(1 << 16);
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<!-- Artio dictionary generated by com.demo.artio.dictionary.ConvertDictionary. -->\n");
        xml.append("<fix");
        if (dictionary.specType() != null) {
            attribute(xml, "type", dictionary.specType());
        }
        attribute(xml, "major", Integer.toString(dictionary.major()));
        attribute(xml, "minor", Integer.toString(dictionary.minor()));
        if (dictionary.servicePack() != null) {
            attribute(xml, "servicepack", dictionary.servicePack());
        }
        xml.append(">\n");

        aggregate(xml, "header", dictionary.header(), 1);
        aggregate(xml, "trailer", dictionary.trailer(), 1);

        indent(xml, 1).append("<messages>\n");
        for (final MessageDef message : dictionary.messages()) {
            indent(xml, 2).append("<message");
            attribute(xml, "name", message.name());
            attribute(xml, "msgtype", message.msgType());
            attribute(xml, "msgcat", message.msgCat() == null ? "app" : message.msgCat());
            if (message.entries().isEmpty()) {
                xml.append("/>\n");
            } else {
                xml.append(">\n");
                entries(xml, message.entries(), 3);
                indent(xml, 2).append("</message>\n");
            }
        }
        indent(xml, 1).append("</messages>\n");

        if (!dictionary.components().isEmpty()) {
            indent(xml, 1).append("<components>\n");
            for (final ComponentDef component : dictionary.components()) {
                indent(xml, 2).append("<component");
                attribute(xml, "name", component.name());
                if (component.entries().isEmpty()) {
                    xml.append("/>\n");
                } else {
                    xml.append(">\n");
                    entries(xml, component.entries(), 3);
                    indent(xml, 2).append("</component>\n");
                }
            }
            indent(xml, 1).append("</components>\n");
        }

        indent(xml, 1).append("<fields>\n");
        for (final FieldDef field : dictionary.fields()) {
            indent(xml, 2).append("<field");
            attribute(xml, "number", Integer.toString(field.number()));
            attribute(xml, "name", field.name());
            attribute(xml, "type", field.type());
            if (field.values().isEmpty()) {
                xml.append("/>\n");
            } else {
                xml.append(">\n");
                for (final EnumValue value : field.values()) {
                    indent(xml, 3).append("<value");
                    attribute(xml, "enum", value.representation());
                    attribute(xml, "description", value.description());
                    xml.append("/>\n");
                }
                indent(xml, 2).append("</field>\n");
            }
        }
        indent(xml, 1).append("</fields>\n");

        xml.append("</fix>\n");
        return xml.toString();
    }

    private void aggregate(
            final StringBuilder xml, final String name, final List<DictionaryEntry> entries, final int level) {
        indent(xml, level).append('<').append(name).append(">\n");
        entries(xml, entries, level + 1);
        indent(xml, level).append("</").append(name).append(">\n");
    }

    private void entries(final StringBuilder xml, final List<DictionaryEntry> entries, final int level) {
        for (final DictionaryEntry entry : entries) {
            switch (entry) {
                case FieldRef field -> {
                    indent(xml, level).append("<field");
                    attribute(xml, "name", field.name());
                    attribute(xml, "required", field.required() ? "Y" : "N");
                    xml.append("/>\n");
                }
                case ComponentRef component -> {
                    indent(xml, level).append("<component");
                    attribute(xml, "name", component.name());
                    attribute(xml, "required", component.required() ? "Y" : "N");
                    xml.append("/>\n");
                }
                case GroupRef group -> {
                    indent(xml, level).append("<group");
                    attribute(xml, "name", group.name());
                    attribute(xml, "required", group.required() ? "Y" : "N");
                    if (group.children().isEmpty()) {
                        xml.append("/>\n");
                    } else {
                        xml.append(">\n");
                        entries(xml, group.children(), level + 1);
                        indent(xml, level).append("</group>\n");
                    }
                }
            }
        }
    }

    private static StringBuilder indent(final StringBuilder xml, final int level) {
        return xml.append(INDENT.repeat(level));
    }

    private static void attribute(final StringBuilder xml, final String name, final String value) {
        xml.append(' ').append(name).append("=\"").append(escape(value)).append('"');
    }

    private static String escape(final String value) {
        final StringBuilder escaped = new StringBuilder(value.length());
        for (int i = 0; i < value.length(); i++) {
            final char c = value.charAt(i);
            switch (c) {
                case '&' -> escaped.append("&amp;");
                case '<' -> escaped.append("&lt;");
                case '>' -> escaped.append("&gt;");
                case '"' -> escaped.append("&quot;");
                case '\'' -> escaped.append("&apos;");
                default -> escaped.append(c);
            }
        }
        return escaped.toString();
    }
}
